FROM eclipse-temurin:17-jdk-alpine
MAINTAINER  ghanshyam shukla
WORKDIR /tmp

COPY /target/demo-project-amazon-ecr-ecs-practice-0.0.1-SNAPSHOT.jar /tmp/demo-project-amazon-ecr-ecs-practice.jar
ENTRYPOINT ["java","-jar","demo-project-amazon-ecr-ecs-practice.jar"]

